🔹 NumPy (Numerical Python)

📌 Kiya hai?
NumPy ek Python library hai jo numerical (numbers ke) operations 
ke liye use hoti hai.
Ye specially arrays ke sath kaam karne ke liye bani hai (jaise
 Excel ki rows/columns, lekin zyada fast).

📌 Kiyo use karte hain?

Fast calculations ke liye (normal Python lists se zyada fast hai).

Matrix, scientific computing, aur mathematical calculations ke liye.

Machine Learning, AI, aur Data Science ka base hai.

📌 Best Example (NumPy):

In [1]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a)
print(b)
print(a * b)

[1 2 3 4 5]
[10 20 30 40 50]
[ 10  40  90 160 250]


In [7]:
import numpy as np

# Normal Python list
numbers = [1, 2, 3, 4, 5]

# NumPy array
arr = np.array(numbers)

# Array ke sath operations easy
print(arr * 2)  # Output: [2 4 6 8 10]


[ 2  4  6  8 10]


🔹 Pandas (Python Data Analysis Library)

📌 Kiya hai?
Pandas ek Python library hai jo data ko organize karne, analyze karne aur clean karne ke liye use hoti hai.
Excel ki tarah rows & columns ke format me data handle karti hai.

📌 Kiyo use karte hain?

Data ko easily read/write karne ke liye (CSV, Excel, Database se).

Data ko filter, sort, group aur analyze karne ke liye.

Data Science aur Machine Learning me data cleaning ke liye.

📌 Best Example (Pandas):

In [1]:
import pandas as pd

# Data bana rahe hain
data = {
    'Name': ['Ali', 'Zohaib', 'Sara'],
    'Age': [22, 25, 20]
}

# DataFrame banaya (Excel sheet jaisa)
df = pd.DataFrame(data)

print(df)


     Name  Age
0     Ali   22
1  Zohaib   25
2    Sara   20


🔹 List (Python ka normal data structure)

📌 Kiya hai?
List ek flexible container hai jisme hum different types ka data rakh sakte hain (numbers, strings, objects sab ek sath).

Ye dynamic hai: size change kar sakte ho.

Har element alag type ka ho sakta hai.

📌 Kiyo use karte hain?

Jab mixed data chahiye (e.g. name, age, marks).

Python ka basic built-in data structure hai.

Easy to use, beginners ke liye best.

📌 Example (List):

In [2]:
# Python list example
my_list = [10, "Zohaib", 3.5, True]

print(my_list)        # [10, 'Zohaib', 3.5, True]
print(my_list[1])     # 'Zohaib'
my_list.append(99)    # Element add
print(my_list)        # [10, 'Zohaib', 3.5, True, 99]


[10, 'Zohaib', 3.5, True]
Zohaib
[10, 'Zohaib', 3.5, True, 99]


🔹 Array (NumPy array)

📌 Kiya hai?
Array ek container hai jo sirf same type ke data ko store karta hai (mostly numbers).

Ye fast hota hai aur large data ke liye best hai.

Mathematical calculations ke liye bana hai.

📌 Kiyo use karte hain?

Jab speed aur performance important ho.

Scientific calculations, Machine Learning, Data Science me.

📌 Example (Array):

In [3]:
import numpy as np

# NumPy array
arr = np.array([10, 20, 30, 40])

print(arr)         # [10 20 30 40]
print(arr * 2)     # [20 40 60 80]


[10 20 30 40]
[20 40 60 80]
