In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

print(np.concatenate([a, b]))

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
z = np.array([11, 12, 13, 14, 15])

print(np.append(a,[89]))
print(np.insert(a, 1,[45]))

[ 1  2  3  4  5 89]
[ 1 45  2  3  4  5]
