In [1]:
import numpy as np

In [4]:
# sort 

a = np.array([1,11,3,56,76, 2,12, 3,455, 4,6788, 5,10])
print(np.sort(a))

[   1    2    3    3    4    5   10   11   12   56   76  455 6788]


In [11]:
# Filter
b = np.array([1,11,3,10])

f = np.sort(b)

f = [True, True, True, False]

fa = b[f]

print(fa)





[ 1 11  3]


In [ ]:
# Search
b = np.array([1,11,3,56,76, 2,12, 3,455, 4,6788, 5,10])

s : int = np.where(b == 3)
# s  = np.where(b % 2 == 0) 
print(s)



(array([ 3,  4,  5,  6,  9, 10, 12]),)


<h1> Aggregating Functions in Numpy</h1>

In [12]:
import numpy as np

In [16]:
a = np.array([1,2,3,4,5])

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))
print(np.cumsum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))

3.0
3.0
1.4142135623730951
2.0
15
[ 1  3  6 10 15]
1
5
5
